name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2021-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Compile and run tests on robot code
      run: ./gradlew build -Dnashorn.args=--no-deprecation-warning